#pragma once
void TestModeReach();
void testMod1();
void testMod3();
void testCoro();
void testjthread();
void testLatch();
void testLatchReady();
void testBarrier();
void testSemaphore();
void testSemaphoreNotify();
void testAtomicRef();
void testAtomicShared();
void testAtomicWeak();
void testAtomicWait();
void testAtomicTicket();
void testAsyncStream();
